### ISSUE TITLE
请教一下，遇到和楼上同样的问题

### ISSUE THREAD

**Issue by chunshuiqing** [luqin/blog#21]

**Comment by chunshuiqing** [comment]
cnpm_package cnpm install @my-company-name/tmp
⠼ [0/1] Installing @my-company-name/tmp@*[@my-company-name/tmp@1.0.0] download Error: GET http://r.cnpmjs.org/@my-company-name/tmp/download/@my-company-name/tmp-1.0.0.tgz response 404 status, fail count: 1
⠸ [0/1] Installing @my-company-name/tmp@*[@my-company-name/tmp@1.0.0] download Error: GET http://r.cnpmjs.org/@my-company-name/tmp/download/@my-company-name/tmp-1.0.0.tgz response 404 status, fail count: 2
⠧ [0/1] Installing @my-company-name/tmp@*[@my-company-name/tmp@1.0.0] download Error: GET http://r.cnpmjs.org/@my-company-name/tmp/download/@my-company-name/tmp-1.0.0.tgz response 404 status, fail count: 3
✖ Install fail! Error: GET http://r.cnpmjs.org/@my-company-name/tmp/download/@my-company-name/tmp-1.0.0.tgz response 404 status
Error: GET http://r.cnpmjs.org/@my-company-name/tmp/download/@my-company-name/tmp-1.0.0.tgz response 404 status
    at get (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:57:17)
    at get.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at <anonymous>
npminstall version: 3.10.0
npminstall args: /usr/local/Cellar/node/8.7.0/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/a123456/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://localhost:7001/ @my-company-name/tmp

**Comment by chunshuiqing** [comment]
下载release的库就好了
